### ISSUE TITLE
Ein Schiff mit Kiste soll langsamer werden

### ISSUE THREAD

**Issue by Sl3vin** [MaxPlay/GGJ2021#5]
**Ein Schiff mit Kiste ist langsamer**

*Reference: [Schiff](https://github.com/MaxPlay/GGJ2021/projects/1#card-53851328)*

*Reference: [Hindernis:Kisten](https://github.com/MaxPlay/GGJ2021/projects/1#card-53853230)*

**Comment by MaxPlay** [comment]
Fixed in d4442dba29df9e5cd86f9cb0613363544c3bda43
